config/routes.rb
Rails.application.routes.draw do

  # resources :easyforms
  # devise_for :users
  post 'easyforms/:email', to: 'easyforms#create'
  
  root to: 'static_pages#home'

  #  get 'static_pages/help'  
  #  get 'static_pages/about'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/easyform.rb
class Easyform < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/easyforms_controller.rb
class EasyformsController < ApplicationController
  before_action :set_easyform, only: [:show, :edit, :update, :destroy]

  # GET /easyforms
  # GET /easyforms.json
  def index
    @easyforms = Easyform.all
  end

  # GET /easyforms/1
  # GET /easyforms/1.json
  def show
  end

  # GET /easyforms/new
  def new
    @easyform = Easyform.new
  end

  # GET /easyforms/1/edit
  def edit
  end

  # POST /easyforms
  # POST /easyforms.json
  def create
    @easyform = Easyform.new(easyform_params)

    respond_to do |format|
      if @easyform.save
        format.html { redirect_to @easyform, notice: 'Easyform was successfully created.' }
        format.json { render :show, status: :created, location: @easyform }
      else
        format.html { render :new }
        format.json { render json: @easyform.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /easyforms/1
  # PATCH/PUT /easyforms/1.json
  def update
    respond_to do |format|
      if @easyform.update(easyform_params)
        format.html { redirect_to @easyform, notice: 'Easyform was successfully updated.' }
        format.json { render :show, status: :ok, location: @easyform }
      else
        format.html { render :edit }
        format.json { render json: @easyform.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /easyforms/1
  # DELETE /easyforms/1.json
  def destroy
    @easyform.destroy
    respond_to do |format|
      format.html { redirect_to easyforms_url, notice: 'Easyform was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_easyform
      @easyform = Easyform.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def easyform_params
      params.require(:easyform).permit(:receiver, :form_fields)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/easyforms_helper.rb
module EasyformsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/easyforms/_form.html.erb
<%= form_with(model: easyform, local: true) do |form| %>
  <% if easyform.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(easyform.errors.count, "error") %> prohibited this easyform from being saved:</h2>

      <ul>
      <% easyform.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :receiver %>
    <%= form.text_field :receiver, id: :easyform_receiver %>
  </div>

  <div class="field">
    <%= form.label :form_fields %>
    <%= form.text_field :form_fields, id: :easyform_form_fields %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/easyforms/edit.html.erb
<h1>Editing Easyform</h1>

<%= render 'form', easyform: @easyform %>

<%= link_to 'Show', @easyform %> |
<%= link_to 'Back', easyforms_path %>

app/views/easyforms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Easyforms</h1>

<table>
  <thead>
    <tr>
      <th>Receiver</th>
      <th>Form fields</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @easyforms.each do |easyform| %>
      <tr>
        <td><%= easyform.receiver %></td>
        <td><%= easyform.form_fields %></td>
        <td><%= link_to 'Show', easyform %></td>
        <td><%= link_to 'Edit', edit_easyform_path(easyform) %></td>
        <td><%= link_to 'Destroy', easyform, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Easyform', new_easyform_path %>

app/views/easyforms/new.html.erb
<h1>New Easyform</h1>

<%= render 'form', easyform: @easyform %>

<%= link_to 'Back', easyforms_path %>

app/views/easyforms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Receiver:</strong>
  <%= @easyform.receiver %>
</p>

<p>
  <strong>Form fields:</strong>
  <%= @easyform.form_fields %>
</p>

<%= link_to 'Edit', edit_easyform_path(@easyform) %> |
<%= link_to 'Back', easyforms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
	<title>ICanbuildyourWebsite</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all' %>
    </head>

    <body>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

	<%= yield %>
    </body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>